/**
 * inject-lattice.ts — wire the lattice substrate into every .claude/agents/*.md file.
 *
 * Reads .claude/lattices/{product-outline,journey-lattice,sentiment-lattice,knowledge-lattice}.md,
 * concatenates them inside a marker-bounded block, and injects (or refreshes) the block
 * into each agent markdown file under .claude/agents/.
 *
 * Sub-agents launched via the Agent tool do NOT inherit CLAUDE.md @imports
 * (Audit finding #2, May 13 2026). Without inline injection, the lattice substrate
 * is invisible to sub-agents. This script is the inline-injection surface.
 *
 * Modes:
 *   npx tsx scripts/inject-lattice.ts            # write/refresh
 *   npx tsx scripts/inject-lattice.ts --check    # verify manifest matches current lattice; exit 1 on drift
 *
 * Outputs a manifest at .claude/agents/_lattice-manifest.json mapping each agent
 * file to the SHA-256 of its injected lattice block. CI/pre-commit can run --check
 * to fail when lattice drifted in a commit that didn't refresh agents.
 */

import * as fs from "fs";
import * as path from "path";
import * as crypto from "crypto";

const ROOT = path.resolve(__dirname, "..");
const LATTICE_DIR = path.join(ROOT, ".claude", "lattices");
const AGENT_DIR = path.join(ROOT, ".claude", "agents");
const MANIFEST_PATH = path.join(AGENT_DIR, "_lattice-manifest.json");

const BEGIN = "<!-- BEGIN LATTICE INJECTION -->";
const END = "<!-- END LATTICE INJECTION -->";

const LATTICE_FILES = [
  "product-outline.md",
  "journey-lattice.md",
  "sentiment-lattice.md",
  "knowledge-lattice.md",
];

function buildLatticeBlock(): { block: string; hash: string } {
  const parts: string[] = [];
  parts.push(BEGIN);
  parts.push("<!-- Auto-generated by scripts/inject-lattice.ts. Edit lattice source files, not this block. -->");
  parts.push("");
  parts.push("# Alloro Lattice Substrate (inlined for sub-agents)");
  parts.push("");
  parts.push("Sub-agents do not inherit CLAUDE.md @imports. This block is the substrate every Alloro sub-agent reads before producing output.");
  parts.push("");
  for (const filename of LATTICE_FILES) {
    const content = fs.readFileSync(path.join(LATTICE_DIR, filename), "utf-8").trimEnd();
    parts.push(`<!-- source: .claude/lattices/${filename} -->`);
    parts.push(content);
    parts.push("");
  }
  parts.push(END);
  const block = parts.join("\n") + "\n";
  const hash = crypto.createHash("sha256").update(block).digest("hex");
  return { block, hash };
}

function injectOrReplace(fileContent: string, latticeBlock: string): string {
  const beginIdx = fileContent.indexOf(BEGIN);
  const endIdx = fileContent.indexOf(END);
  if (beginIdx === -1 || endIdx === -1) {
    const sep = fileContent.endsWith("\n") ? "" : "\n";
    return `${fileContent}${sep}\n${latticeBlock}`;
  }
  const before = fileContent.slice(0, beginIdx);
  const after = fileContent.slice(endIdx + END.length);
  return `${before}${latticeBlock.trimEnd()}${after}`;
}

function getAgentFiles(): string[] {
  return fs
    .readdirSync(AGENT_DIR)
    .filter((f) => f.endsWith(".md") && !f.startsWith("_"))
    .map((f) => path.join(AGENT_DIR, f))
    .sort();
}

function fileBlockHash(filePath: string): string | null {
  const content = fs.readFileSync(filePath, "utf-8");
  const beginIdx = content.indexOf(BEGIN);
  const endIdx = content.indexOf(END);
  if (beginIdx === -1 || endIdx === -1) return null;
  const block = content.slice(beginIdx, endIdx + END.length) + "\n";
  return crypto.createHash("sha256").update(block).digest("hex");
}

function runWrite(): void {
  const { block, hash } = buildLatticeBlock();
  const manifest: { generatedAt: string; latticeHash: string; agents: Record<string, string> } = {
    generatedAt: new Date().toISOString(),
    latticeHash: hash,
    agents: {},
  };
  const agentFiles = getAgentFiles();
  let written = 0;
  for (const filePath of agentFiles) {
    const original = fs.readFileSync(filePath, "utf-8");
    const updated = injectOrReplace(original, block);
    if (updated !== original) {
      fs.writeFileSync(filePath, updated);
      written += 1;
    }
    manifest.agents[path.basename(filePath)] = hash;
  }
  fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + "\n");
  console.log(`[inject-lattice] lattice hash: ${hash}`);
  console.log(`[inject-lattice] agents touched: ${written} of ${agentFiles.length}`);
  console.log(`[inject-lattice] manifest: ${path.relative(ROOT, MANIFEST_PATH)}`);
}

function runCheck(): never {
  const { hash: expected } = buildLatticeBlock();
  if (!fs.existsSync(MANIFEST_PATH)) {
    console.error(`[inject-lattice] --check FAIL: manifest missing at ${MANIFEST_PATH}`);
    process.exit(1);
  }
  const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf-8"));
  if (manifest.latticeHash !== expected) {
    console.error(`[inject-lattice] --check FAIL: lattice content changed.`);
    console.error(`  expected: ${expected}`);
    console.error(`  manifest: ${manifest.latticeHash}`);
    console.error(`  run: npx tsx scripts/inject-lattice.ts`);
    process.exit(1);
  }
  const agentFiles = getAgentFiles();
  const drift: string[] = [];
  for (const filePath of agentFiles) {
    const name = path.basename(filePath);
    const actual = fileBlockHash(filePath);
    if (actual !== expected) {
      drift.push(`${name} (block ${actual ?? "missing"})`);
    }
  }
  if (drift.length > 0) {
    console.error(`[inject-lattice] --check FAIL: ${drift.length} agent files out of sync:`);
    for (const d of drift) console.error(`  - ${d}`);
    console.error(`  run: npx tsx scripts/inject-lattice.ts`);
    process.exit(1);
  }
  console.log(`[inject-lattice] --check OK (${agentFiles.length} agents, hash ${expected})`);
  process.exit(0);
}

const mode = process.argv.slice(2).includes("--check") ? "check" : "write";
if (mode === "check") {
  runCheck();
} else {
  runWrite();
}
